<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.4" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.4" />
        <PackageReference Include="LazyCache" Version="2.4.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Assignment.Contracts\Assignment.Contracts.csproj" />
    </ItemGroup>

</Project>
